// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module AXI_DMA_SLAVE_Block_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stream_in_TDATA,
        stream_in_TVALID,
        stream_in_TREADY,
        stream_in_TLAST,
        stream_out_V_V_din,
        stream_out_V_V_full_n,
        stream_out_V_V_write
);

parameter    ap_ST_fsm_state1 = 23'd1;
parameter    ap_ST_fsm_state2 = 23'd2;
parameter    ap_ST_fsm_state3 = 23'd4;
parameter    ap_ST_fsm_state4 = 23'd8;
parameter    ap_ST_fsm_state5 = 23'd16;
parameter    ap_ST_fsm_state6 = 23'd32;
parameter    ap_ST_fsm_state7 = 23'd64;
parameter    ap_ST_fsm_state8 = 23'd128;
parameter    ap_ST_fsm_state9 = 23'd256;
parameter    ap_ST_fsm_state10 = 23'd512;
parameter    ap_ST_fsm_state11 = 23'd1024;
parameter    ap_ST_fsm_state12 = 23'd2048;
parameter    ap_ST_fsm_state13 = 23'd4096;
parameter    ap_ST_fsm_state14 = 23'd8192;
parameter    ap_ST_fsm_pp0_stage0 = 23'd16384;
parameter    ap_ST_fsm_state17 = 23'd32768;
parameter    ap_ST_fsm_state18 = 23'd65536;
parameter    ap_ST_fsm_state19 = 23'd131072;
parameter    ap_ST_fsm_state20 = 23'd262144;
parameter    ap_ST_fsm_state21 = 23'd524288;
parameter    ap_ST_fsm_state22 = 23'd1048576;
parameter    ap_ST_fsm_state23 = 23'd2097152;
parameter    ap_ST_fsm_pp1_stage0 = 23'd4194304;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] stream_in_TDATA;
input   stream_in_TVALID;
output   stream_in_TREADY;
input   stream_in_TLAST;
output  [7:0] stream_out_V_V_din;
input   stream_out_V_V_full_n;
output   stream_out_V_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stream_out_V_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [22:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] stream_in_V_data_V_0_data_out;
wire    stream_in_V_data_V_0_vld_in;
wire    stream_in_V_data_V_0_vld_out;
wire    stream_in_V_data_V_0_ack_in;
reg    stream_in_V_data_V_0_ack_out;
reg   [7:0] stream_in_V_data_V_0_payload_A;
reg   [7:0] stream_in_V_data_V_0_payload_B;
reg    stream_in_V_data_V_0_sel_rd;
reg    stream_in_V_data_V_0_sel_wr;
wire    stream_in_V_data_V_0_sel;
wire    stream_in_V_data_V_0_load_A;
wire    stream_in_V_data_V_0_load_B;
reg   [1:0] stream_in_V_data_V_0_state;
wire    stream_in_V_data_V_0_state_cmp_full;
wire    stream_in_V_last_0_vld_in;
reg    stream_in_V_last_0_ack_out;
reg   [1:0] stream_in_V_last_0_state;
reg    stream_in_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage0;
reg   [0:0] tmp_71_reg_311;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_72_reg_272;
reg    stream_out_V_V_blk_n;
reg   [28:0] i1_reg_65;
reg   [28:0] i_reg_76;
wire   [0:0] tmp_s_fu_92_p2;
reg   [0:0] tmp_s_reg_200;
reg    ap_block_state2;
reg  signed [7:0] tmp_data_V_1_reg_204;
reg    ap_block_state3;
reg  signed [7:0] tmp_data_V_2_reg_209;
reg    ap_block_state4;
reg  signed [7:0] tmp_data_V_3_reg_215;
reg    ap_block_state5;
reg  signed [7:0] tmp_data_V_4_reg_221;
reg    ap_block_state6;
reg  signed [7:0] tmp_data_V_5_reg_227;
reg    ap_block_state7;
wire   [15:0] r_V_4_fu_104_p2;
reg  signed [15:0] r_V_4_reg_232;
reg    ap_block_state8;
wire   [15:0] r_V_fu_116_p2;
reg  signed [15:0] r_V_reg_237;
wire    ap_CS_fsm_state9;
wire  signed [23:0] grp_fu_176_p2;
reg  signed [23:0] r_V_5_reg_252;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire  signed [29:0] grp_fu_182_p2;
reg  signed [29:0] r_V_6_reg_267;
wire    ap_CS_fsm_state14;
wire   [0:0] tmp_72_fu_138_p2;
wire    ap_block_state15_pp0_stage0_iter0;
reg    ap_block_state16_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [28:0] i_4_fu_143_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_CS_fsm_state18;
wire  signed [23:0] grp_fu_188_p2;
reg  signed [23:0] r_V_7_reg_291;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire  signed [29:0] grp_fu_194_p2;
reg  signed [29:0] r_V_s_reg_306;
wire    ap_CS_fsm_state23;
wire   [0:0] tmp_71_fu_165_p2;
wire    ap_block_state24_pp1_stage0_iter0;
reg    ap_block_state25_pp1_stage0_iter1;
reg    ap_block_pp1_stage0_11001;
wire   [28:0] i_s_fu_170_p2;
reg    ap_enable_reg_pp1_iter0;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state15;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state24;
reg    ap_block_pp0_stage0_01001;
reg    ap_block_pp1_stage0_01001;
wire  signed [7:0] r_V_4_fu_104_p0;
wire  signed [7:0] r_V_4_fu_104_p1;
wire  signed [7:0] r_V_fu_116_p0;
wire  signed [7:0] r_V_fu_116_p1;
wire   [29:0] i1_cast_fu_134_p1;
wire   [29:0] i_cast_fu_161_p1;
wire    ap_CS_fsm_state17;
reg   [22:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 23'd1;
#0 stream_in_V_data_V_0_sel_rd = 1'b0;
#0 stream_in_V_data_V_0_sel_wr = 1'b0;
#0 stream_in_V_data_V_0_state = 2'd0;
#0 stream_in_V_last_0_state = 2'd0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
end

cnn_mul_mul_16s_8bkb #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
cnn_mul_mul_16s_8bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(r_V_4_reg_232),
    .din1(tmp_data_V_2_reg_209),
    .ce(1'b1),
    .dout(grp_fu_176_p2)
);

cnn_mul_mul_24s_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 30 ))
cnn_mul_mul_24s_8cud_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(r_V_5_reg_252),
    .din1(tmp_data_V_2_reg_209),
    .ce(1'b1),
    .dout(grp_fu_182_p2)
);

cnn_mul_mul_16s_8bkb #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
cnn_mul_mul_16s_8bkb_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(r_V_reg_237),
    .din1(tmp_data_V_4_reg_221),
    .ce(1'b1),
    .dout(grp_fu_188_p2)
);

cnn_mul_mul_24s_8cud #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 30 ))
cnn_mul_mul_24s_8cud_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(r_V_7_reg_291),
    .din1(tmp_data_V_1_reg_204),
    .ce(1'b1),
    .dout(grp_fu_194_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state17)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state15) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state14)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state15))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state15);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b1 == ap_CS_fsm_state14)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state24) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state23)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state24))) begin
            ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state24);
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if ((1'b1 == ap_CS_fsm_state23)) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        stream_in_V_data_V_0_sel_rd <= 1'b0;
    end else begin
        if (((stream_in_V_data_V_0_ack_out == 1'b1) & (stream_in_V_data_V_0_vld_out == 1'b1))) begin
            stream_in_V_data_V_0_sel_rd <= ~stream_in_V_data_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        stream_in_V_data_V_0_sel_wr <= 1'b0;
    end else begin
        if (((stream_in_V_data_V_0_ack_in == 1'b1) & (stream_in_V_data_V_0_vld_in == 1'b1))) begin
            stream_in_V_data_V_0_sel_wr <= ~stream_in_V_data_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        stream_in_V_data_V_0_state <= 2'd0;
    end else begin
        if ((((stream_in_V_data_V_0_state == 2'd2) & (stream_in_V_data_V_0_vld_in == 1'b0)) | ((stream_in_V_data_V_0_state == 2'd3) & (stream_in_V_data_V_0_vld_in == 1'b0) & (stream_in_V_data_V_0_ack_out == 1'b1)))) begin
            stream_in_V_data_V_0_state <= 2'd2;
        end else if ((((stream_in_V_data_V_0_state == 2'd1) & (stream_in_V_data_V_0_ack_out == 1'b0)) | ((stream_in_V_data_V_0_state == 2'd3) & (stream_in_V_data_V_0_ack_out == 1'b0) & (stream_in_V_data_V_0_vld_in == 1'b1)))) begin
            stream_in_V_data_V_0_state <= 2'd1;
        end else if (((~((stream_in_V_data_V_0_vld_in == 1'b0) & (stream_in_V_data_V_0_ack_out == 1'b1)) & ~((stream_in_V_data_V_0_ack_out == 1'b0) & (stream_in_V_data_V_0_vld_in == 1'b1)) & (stream_in_V_data_V_0_state == 2'd3)) | ((stream_in_V_data_V_0_state == 2'd1) & (stream_in_V_data_V_0_ack_out == 1'b1)) | ((stream_in_V_data_V_0_state == 2'd2) & (stream_in_V_data_V_0_vld_in == 1'b1)))) begin
            stream_in_V_data_V_0_state <= 2'd3;
        end else begin
            stream_in_V_data_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        stream_in_V_last_0_state <= 2'd0;
    end else begin
        if ((((stream_in_V_last_0_state == 2'd2) & (stream_in_V_last_0_vld_in == 1'b0)) | ((stream_in_V_last_0_state == 2'd3) & (stream_in_V_last_0_vld_in == 1'b0) & (stream_in_V_last_0_ack_out == 1'b1)))) begin
            stream_in_V_last_0_state <= 2'd2;
        end else if ((((stream_in_V_last_0_state == 2'd1) & (stream_in_V_last_0_ack_out == 1'b0)) | ((stream_in_V_last_0_state == 2'd3) & (stream_in_V_last_0_ack_out == 1'b0) & (stream_in_V_last_0_vld_in == 1'b1)))) begin
            stream_in_V_last_0_state <= 2'd1;
        end else if (((~((stream_in_V_last_0_vld_in == 1'b0) & (stream_in_V_last_0_ack_out == 1'b1)) & ~((stream_in_V_last_0_ack_out == 1'b0) & (stream_in_V_last_0_vld_in == 1'b1)) & (stream_in_V_last_0_state == 2'd3)) | ((stream_in_V_last_0_state == 2'd1) & (stream_in_V_last_0_ack_out == 1'b1)) | ((stream_in_V_last_0_state == 2'd2) & (stream_in_V_last_0_vld_in == 1'b1)))) begin
            stream_in_V_last_0_state <= 2'd3;
        end else begin
            stream_in_V_last_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_72_fu_138_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i1_reg_65 <= i_4_fu_143_p2;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        i1_reg_65 <= 29'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_71_fu_165_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        i_reg_76 <= i_s_fu_170_p2;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        i_reg_76 <= 29'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (tmp_s_reg_200 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        r_V_4_reg_232 <= r_V_4_fu_104_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        r_V_5_reg_252 <= grp_fu_176_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        r_V_6_reg_267 <= grp_fu_182_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        r_V_7_reg_291 <= grp_fu_188_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (tmp_s_reg_200 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        r_V_reg_237 <= r_V_fu_116_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        r_V_s_reg_306 <= grp_fu_194_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((stream_in_V_data_V_0_load_A == 1'b1)) begin
        stream_in_V_data_V_0_payload_A <= stream_in_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((stream_in_V_data_V_0_load_B == 1'b1)) begin
        stream_in_V_data_V_0_payload_B <= stream_in_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        tmp_71_reg_311 <= tmp_71_fu_165_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_72_reg_272 <= tmp_72_fu_138_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_1_reg_204 <= stream_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_data_V_2_reg_209 <= stream_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_data_V_3_reg_215 <= stream_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        tmp_data_V_4_reg_221 <= stream_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
        tmp_data_V_5_reg_227 <= stream_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_s_reg_200 <= tmp_s_fu_92_p2;
    end
end

always @ (*) begin
    if ((tmp_72_fu_138_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state15 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state15 = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_71_fu_165_p2 == 1'd0)) begin
        ap_condition_pp1_exit_iter0_state24 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state24 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((tmp_72_reg_272 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_71_reg_311 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        stream_in_TDATA_blk_n = stream_in_V_data_V_0_state[1'd0];
    end else begin
        stream_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((tmp_72_reg_272 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_71_reg_311 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)))) begin
        stream_in_V_data_V_0_ack_out = 1'b1;
    end else begin
        stream_in_V_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((stream_in_V_data_V_0_sel == 1'b1)) begin
        stream_in_V_data_V_0_data_out = stream_in_V_data_V_0_payload_B;
    end else begin
        stream_in_V_data_V_0_data_out = stream_in_V_data_V_0_payload_A;
    end
end

always @ (*) begin
    if ((((tmp_72_reg_272 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_71_reg_311 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)))) begin
        stream_in_V_last_0_ack_out = 1'b1;
    end else begin
        stream_in_V_last_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((tmp_72_reg_272 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_71_reg_311 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        stream_out_V_V_blk_n = stream_out_V_V_full_n;
    end else begin
        stream_out_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((tmp_72_reg_272 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_71_reg_311 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2)))) begin
        stream_out_V_V_write = 1'b1;
    end else begin
        stream_out_V_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if ((~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if ((~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (tmp_s_reg_200 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else if ((~((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0)) & (tmp_s_reg_200 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((tmp_72_fu_138_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((tmp_72_fu_138_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((tmp_71_fu_165_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((tmp_71_fu_165_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_72_reg_272 == 1'd1) & (stream_out_V_V_full_n == 1'b0)) | ((tmp_72_reg_272 == 1'd1) & (stream_in_V_data_V_0_vld_out == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_72_reg_272 == 1'd1) & (stream_out_V_V_full_n == 1'b0)) | ((tmp_72_reg_272 == 1'd1) & (stream_in_V_data_V_0_vld_out == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_72_reg_272 == 1'd1) & (stream_out_V_V_full_n == 1'b0)) | ((tmp_72_reg_272 == 1'd1) & (stream_in_V_data_V_0_vld_out == 1'b0))));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = ((ap_enable_reg_pp1_iter1 == 1'b1) & (((tmp_71_reg_311 == 1'd1) & (stream_out_V_V_full_n == 1'b0)) | ((tmp_71_reg_311 == 1'd1) & (stream_in_V_data_V_0_vld_out == 1'b0))));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = ((ap_enable_reg_pp1_iter1 == 1'b1) & (((tmp_71_reg_311 == 1'd1) & (stream_out_V_V_full_n == 1'b0)) | ((tmp_71_reg_311 == 1'd1) & (stream_in_V_data_V_0_vld_out == 1'b0))));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = ((ap_enable_reg_pp1_iter1 == 1'b1) & (((tmp_71_reg_311 == 1'd1) & (stream_out_V_V_full_n == 1'b0)) | ((tmp_71_reg_311 == 1'd1) & (stream_in_V_data_V_0_vld_out == 1'b0))));
end

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_block_state15_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state16_pp0_stage0_iter1 = (((tmp_72_reg_272 == 1'd1) & (stream_out_V_V_full_n == 1'b0)) | ((tmp_72_reg_272 == 1'd1) & (stream_in_V_data_V_0_vld_out == 1'b0)));
end

always @ (*) begin
    ap_block_state2 = ((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0));
end

assign ap_block_state24_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state25_pp1_stage0_iter1 = (((tmp_71_reg_311 == 1'd1) & (stream_out_V_V_full_n == 1'b0)) | ((tmp_71_reg_311 == 1'd1) & (stream_in_V_data_V_0_vld_out == 1'b0)));
end

always @ (*) begin
    ap_block_state3 = ((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state4 = ((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state5 = ((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state6 = ((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state7 = ((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state8 = ((stream_in_V_data_V_0_vld_out == 1'b0) | (stream_out_V_V_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign i1_cast_fu_134_p1 = i1_reg_65;

assign i_4_fu_143_p2 = (i1_reg_65 + 29'd1);

assign i_cast_fu_161_p1 = i_reg_76;

assign i_s_fu_170_p2 = (i_reg_76 + 29'd1);

assign r_V_4_fu_104_p0 = tmp_data_V_5_reg_227;

assign r_V_4_fu_104_p1 = tmp_data_V_3_reg_215;

assign r_V_4_fu_104_p2 = ($signed(r_V_4_fu_104_p0) * $signed(r_V_4_fu_104_p1));

assign r_V_fu_116_p0 = tmp_data_V_4_reg_221;

assign r_V_fu_116_p1 = tmp_data_V_3_reg_215;

assign r_V_fu_116_p2 = ($signed(r_V_fu_116_p0) * $signed(r_V_fu_116_p1));

assign stream_in_TREADY = stream_in_V_last_0_state[1'd1];

assign stream_in_V_data_V_0_ack_in = stream_in_V_data_V_0_state[1'd1];

assign stream_in_V_data_V_0_load_A = (stream_in_V_data_V_0_state_cmp_full & ~stream_in_V_data_V_0_sel_wr);

assign stream_in_V_data_V_0_load_B = (stream_in_V_data_V_0_state_cmp_full & stream_in_V_data_V_0_sel_wr);

assign stream_in_V_data_V_0_sel = stream_in_V_data_V_0_sel_rd;

assign stream_in_V_data_V_0_state_cmp_full = ((stream_in_V_data_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign stream_in_V_data_V_0_vld_in = stream_in_TVALID;

assign stream_in_V_data_V_0_vld_out = stream_in_V_data_V_0_state[1'd0];

assign stream_in_V_last_0_vld_in = stream_in_TVALID;

assign stream_out_V_V_din = stream_in_V_data_V_0_data_out;

assign tmp_71_fu_165_p2 = (($signed(i_cast_fu_161_p1) < $signed(r_V_s_reg_306)) ? 1'b1 : 1'b0);

assign tmp_72_fu_138_p2 = (($signed(i1_cast_fu_134_p1) < $signed(r_V_6_reg_267)) ? 1'b1 : 1'b0);

assign tmp_s_fu_92_p2 = ((stream_in_V_data_V_0_data_out == 8'd0) ? 1'b1 : 1'b0);

endmodule //AXI_DMA_SLAVE_Block_s
